{% set name = "fanstatic" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 612104b3978469828ba0e80c0cd68532670e7a65e3acc00650309b68795a51a3

build:
  noarch: python
  number: 1
  entry_points:
    - fanstatic-compile = fanstatic.compiler:compile_resources
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - shutilwhich
    - webob >=1.2

test:
  imports:
    - fanstatic
  commands:
    - fanstatic-compile --help
  requires:
    - closure
    - cssmin
    - jsmin
    - pytest >=2.3
    - python {{ python_min }}

about:
  home: http://fanstatic.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Flexible static resources for web applications
  doc_url: http://www.fanstatic.org/en/latest/
  dev_url: https://bitbucket.org/fanstatic/fanstatic/src/default/

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
